#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2015 - 2026 Rime community
#
# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the pinyin syllable table for the T9 disambiguation feature.

The table lists every standard pinyin syllable (no tone) with three derived
codes used by the app-side T9 disambiguation decoder
(`app/src/main/java/com/osfans/trime/ime/disambiguation/T9PinyinDecoder.kt`):

- t9_code:      full pinyin folded to T9 digits (A-Z -> 22233344455566677778889999)
- flypy_code:   小鹤双拼 key code (initial key + final key)
- flypy_t9_code: the 小鹤双拼 code folded to T9 digits

The syllable list is extracted from the built-in luna_pinyin dictionary so it
matches the actual pinyin space of the bundled Rime data. 小鹤双拼 key mapping
is the standard one (initial table + final table).

Usage:
  python3 script/generate_pinyin_syllables.py > syllables.yaml

The emitted YAML is meant to be pasted into the `t9_disambiguation.syllables`
section of `<schemaId>.extended.yaml` files.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# 小鹤双拼 key mapping (方案特定数据; standard xiaohe layout).
XIAOHE_INITIALS: dict[str, str] = {
    "zh": "v", "ch": "i", "sh": "u",
    "b": "b", "p": "p", "m": "m", "f": "f", "d": "d", "t": "t", "n": "n", "l": "l",
    "g": "g", "k": "k", "h": "h", "j": "j", "q": "q", "x": "x",
    "r": "r", "z": "z", "c": "c", "s": "s", "y": "y", "w": "w",
}

# 小鹤双拼 final keys, mirrored from the wanxiang_algebra.yaml `/base/小鹤双拼`
# preset (the circled-letter -> key xlit there).
XIAOHE_FINALS: dict[str, str] = {
    "a": "a", "o": "o", "e": "e", "i": "i", "u": "u", "v": "v",
    "ai": "d", "ei": "w", "ui": "v", "ao": "c", "ou": "z", "iu": "q",
    "ie": "p", "ve": "t", "ue": "t", "er": "r",
    "an": "j", "en": "f", "in": "b", "un": "y", "vn": "y", "ang": "h",
    "eng": "g", "ing": "k", "ong": "s", "iong": "s",
    "ia": "x", "ua": "x", "uo": "o", "ian": "m", "uan": "r", "iang": "l",
    "uang": "l", "iao": "n", "uai": "k",
    # ü-vowel finals after l/n use the same keys as their u- counterparts.
    "van": "r", "ven": "f", "vin": "b", "vun": "y", "vang": "h",
}

# Standard 9-key fold: letters -> digits on a phone keypad.
LETTER_TO_T9 = {
    letter: str(digit)
    for digit, letters in {
        2: "abc", 3: "def", 4: "ghi", 5: "jkl",
        6: "mno", 7: "pqrs", 8: "tuv", 9: "wxyz",
    }.items()
    for letter in letters
}


def t9_code(s: str) -> str:
    return "".join(LETTER_TO_T9[ch] for ch in s.lower())


def flypy_code(pinyin: str) -> str:
    """Full pinyin -> 小鹤双拼 key code (initial + final)."""
    for init_len in (2, 1):
        initial = pinyin[:init_len]
        final = pinyin[init_len:]
        if initial in XIAOHE_INITIALS and final in XIAOHE_FINALS:
            return XIAOHE_INITIALS[initial] + XIAOHE_FINALS[final]
    # Zero-initial syllables (a, ai, ao, ...): just the final key.
    if pinyin in XIAOHE_FINALS:
        return XIAOHE_FINALS[pinyin]
    raise ValueError(f"cannot encode '{pinyin}' to 小鹤双拼")


# Non-standard interjections present in the dictionary but not valid pinyin
# syllables for the disambiguation table (they have no 小鹤双拼 encoding).
NON_STANDARD = {"eh"}


def extract_syllables() -> set[str]:
    """Unique plain pinyin syllables from the built-in luna_pinyin dict."""
    syllables: set[str] = set()
    dict_file = ROOT / "app/src/main/assets/shared/Default/rime/luna_pinyin.dict.yaml"
    for line in dict_file.read_text(encoding="utf-8").splitlines():
        if not line or line.startswith("#") or line.startswith("---") or line.startswith("..."):
            continue
        parts = line.split("\t")
        if len(parts) < 2:
            continue
        py = parts[1].strip()
        if re.fullmatch(r"[a-zü]+", py):
            syllables.add(py.replace("ü", "v"))
    return syllables


def main() -> int:
    syllables = sorted(extract_syllables() - NON_STANDARD)
    print("# Auto-generated by script/generate_pinyin_syllables.py; do not edit by hand.")
    print("# %d syllables, no tone." % len(syllables))
    for py in syllables:
        fp = flypy_code(py)
        print(
            "    - {pinyin: %s, t9_code: %s, flypy_code: %s, flypy_t9_code: %s}"
            % (py, t9_code(py), fp, t9_code(fp))
        )
    return 0


if __name__ == "__main__":
    sys.exit(main())
